CREATE TABLE EMPLOYEE(
	ID VARCHAR(16) PRIMARY KEY NOT NULL,
    FIRST_NAME VARCHAR(128) NOT NULL,
	LAST_NAME VARCHAR(128) NOT NULL,
	ADDR_CITY VARCHAR(32),
	ADDR_ST VARCHAR(32),
	ADDR_ST_NUM VARCHAR(32),
    DOB VARCHAR(19),
	PHONE VARCHAR(32),
	CELL_PHONE VARCHAR(32),
	DATE_POSITIVE VARCHAR(19) TEXT DEFAULT "not yet",
	DATE_RECOVERY VARCHAR(19) TEXT DEFAULT "not yet"
);

CREATE TABLE COVIDVAC(
	EMPLOYEE_ID VARCHAR(16) NOT NULL,
	DATE_VAC VARCHAR(19) ,
	VAC_MAN VARCHAR(128) NOT NULL,
	VAC_NUM INTEGER,
  FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEES(ID)
  UNIQUE(EMPLOYEE_ID,VAC_NUM)

);

-- ideal
select EMPLOYEE.ID,  FIRST_NAME || ' ' ||LAST_NAME , ADDR_ST || ' ' || ADDR_ST_NUM || ' , ' || ADDR_CITY , DOB , PHONE || ' , ' || CELL_PHONE,COVID ,DATE_POSITIVE ,DATE_RECOVERY,DATE_VAC,VAC_MAN,VAC_NUM 
from EMPLOYEE , COVIDVAC 
  INNER JOIN EMPLOYEE on EMPLOYEE.ID = COVIDVAC.EMPLOYEE_ID 
  ORDER BY LAST_NAME ASC,VAC_NUM ASC

select DOB,  FIRST_NAME || ' ' ||LAST_NAME , ADDR_ST || ' ' || ADDR_ST_NUM || ' , ' || ADDR_CITY , DOB , PHONE || ' , ' || CELL_PHONE ,DATE_POSITIVE ,DATE_RECOVERY,DATE_VAC,VAC_MAN,VAC_NUM 
from EMPLOYEE 
INNER JOIN COVIDVAC on  COVIDVAC.EMPLOYEE_ID= EMPLOYEE.ID 
ORDER BY LAST_NAME ASC,VAC_NUM ASC 

select MAX(VAC_NUM)  from COVIDVAC WHERE EMPLOYEE_ID = "332288372"

-- CREATE TABLE EMPLOYEE(
-- 	ID VARCHAR(16) PRIMARY KEY NOT NULL,
--     FIRST_NAME VARCHAR(128) NOT NULL,
-- 	LAST_NAME VARCHAR(128) NOT NULL,
-- 	ADDR_CITY VARCHAR(32),
-- 	ADDR_ST VARCHAR(32),
-- 	ADDR_ST_NUM VARCHAR(32),
--     DOB VARCHAR(19),
-- 	PHONE VARCHAR(32),
-- 	CELL_PHONE VARCHAR(32)
-- );

-- CREATE TABLE COVID_EMPLOYEE(
-- 	EMPLOYEE_ID VARCHAR(16) PRIMARY KEY NOT NULL,
-- 	DATE_POSITIVE VARCHAR(19) ,
-- 	DATE_RECOVERY VARCHAR(19) 
-- );

-- CREATE TABLE COVIDVAC(
-- 	EMPLOYEE_ID VARCHAR(16) PRIMARY KEY NOT NULL,
-- 	DATE_VAC VARCHAR(19) ,
-- 	VAC_MAN VARCHAR(128) UNIQUE NOT NULL,
-- 	VAC_NUM VARCHAR(1)
-- );

-- INSERT INTO EMPLOYEE VALUES("332288372","Chaya","Henner","JLM","Hatzerot","1","12.05.02","0527695444","0524000035")